
FROM node:16-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock* ./
RUN yarn && yarn cache clean

COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
RUN yarn build

ENV NODE_ENV production

CMD ["./entrypoint.sh"]

