# build image
FROM node:16.20-alpine AS builder

WORKDIR /app

ADD package.json yarn.lock /app/
RUN yarn --pure-lockfile && rm -rf /app/node_modules

# Runtime image from here
FROM node:16.20-alpine AS Product

EXPOSE 8005
WORKDIR /app

# Copy node_modules from builder image
COPY --from=builder /app/package.json /app/yarn.lock ./
COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN yarn build

CMD ["yarn", "docker:start"]
