# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # value must be base64
  mongo-root-password: eXVzaGFrdQo=
  mongo-root-username: eXVzaGFrdQo=
---

